[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Server utils for jsonrpc-core crate."
documentation = "https://docs.rs/jsonrpc-server-utils/"
edition = "2018"
homepage = "https://github.com/paritytech/jsonrpc"
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "serde"]
license = "MIT"
name = "jsonrpc-server-utils"
repository = "https://github.com/paritytech/jsonrpc"
version = "16.0.0"

[dependencies]
bytes05 = { version = "0.5", package = "bytes" }
futures01 = { version = "0.1", package = "futures" }
futures03 = { version = "0.3", package = "futures", features = ["compat"] }
globset = "0.4"
jsonrpc-core = { version = "16.0", path = "../core" }
lazy_static = "1.1.0"
log = "0.4"
tokio-util = { version = "0.3", features = ["codec", "compat"] }
tokio02 = { package = "tokio", version = "0.2", optional = true, features = ["rt-threaded", "io-driver", "io-util", "time", "tcp"] }

unicase = "2.0"

[features]
default = ["tokio02"]

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
